### ISSUE TITLE
Making this a separate issue. Zoom level must be computed from camera distance AND size of viewport on resize.

### ISSUE THREAD

**Issue by DominionSoftware** [OHIF/VTKPlugin#15]
To match OHIF's zoom level, we must compute the scaling percentange (assumption is 1.0 is pixel to screen pixel(?)) from both the camera distance and the size of the viewport (when the user resizes).

**Comment by DominionSoftware** [comment]
Zoom level is computed by calculating the size of the "slice" on the screen divided by the size of the image (for that slice, including the spacing). 

This is now displayed on the screen in rf-plugin7 
A test image was created and measured.
![vtk100pcttest](https://user-images.githubusercontent.com/19329250/46177201-04630200-c280-11e8-9136-16c4feea849a.png)

**Comment by swederik** [comment]
This isn't super important, you can skip it for now.

**Comment by DominionSoftware** [comment]
Its done as of yesterday

Rick Frank
Sent from Mobile
617-838-2031

On Sep 28, 2018, at 5:45 AM, Erik Ziegler <notifications@github.com<mailto:notifications@github.com>> wrote:


This isn't super important, you can skip it for now.
