### ISSUE TITLE
Multiple 3D textures instead viewports

### ISSUE THREAD

**Issue by JorgeVA1994** [OHIF/VTKPlugin#27]
I was testing this plugin to show MPR and VR and I saw that this plugin creates a 3D texture each time the user creates a view. So the problem is that to show MPR and VR the viewer loads some 3D textures instead of sharing them.

I was searching to share resources between contexts in WebGL but I just found workarounds like use one context with differents viewports. My question is if you have some plan like use some workarounds or you preffer to hold the multiple 3D texture load? (maybe I'm wrong, to test this I have just opened the chrome task manager and I looked the GPU memory usage and I have alerted that it increases if you use more views although it is the same texture)

Thanks!

**Comment by pieper** [comment]
This plugin would be able to take advantage of whatever support is provided by webgl and vtkjs for sharing resources across contexts.  Near term I think it's actually easiest to have one rendering context that does all the drawing, but that hasn't been implemented yet.

**Comment by JorgeVA1994** [comment]
Thanks for the reply!
