### ISSUE TITLE
Use correct data type from Display Set for vtkDataArray

### ISSUE THREAD

**Issue by swederik** [OHIF/VTKPlugin#3]
We are currently hardcoding the [vtkDataArray](https://github.com/Kitware/vtk-js/blob/b807950244e1ed7db1ae6858c6829ce33bc32786/Sources/Common/Core/DataArray/index.js) to be backed by an Int16Array:

https://github.com/OHIF/VTKPlugin/blob/982f193b03eed7ad07cc9eda229458a9fb57e3ef/lib/getImageData.js#L27-L35

We need to make this support the actual datatype provided with the display set metadata.

**Comment by DominionSoftware** [comment]
Not sure how to get other data into correct json format or other way to load data. Also need some RBG data to test with

**Comment by swederik** [comment]
https://github.com/OHIF/Viewers/issues/177

Gist is here:

https://gist.github.com/swederik/b7901bd933e6497720783e532616eec0

**Comment by swederik** [comment]
Check image pixelRepresentation (signed) and bitsAllocated to determine data type. Use correct typed array. An example is here: https://github.com/cornerstonejs/cornerstoneWADOImageLoader/blob/b468ad706276daa4c3cf6aefb3beca924a588b61/src/shared/decoders/decodeLittleEndian.js#L6

**Comment by pieper** [comment]
The point here is to use the BitsAllocated and the PixelRepresentation to determine the correct array datatype to create.  Also to generate appropriate diagnostics if there isn't a valid mapping.

**Comment by DominionSoftware** [comment]
We now support signed and unsigned 16 bit data. console.asserts() have been put in for 8 bit data (signed and unsigned) as the vtk renderer crashes when using 8 bit data. RGB data makes no sense for these plugins so we also console.assert() on components > 1.

**Comment by pieper** [comment]
console.assert doesn't really do anything except print.  Better to throw an error that can be caught and acted on by the application.

**Comment by DominionSoftware** [comment]
Agreed. I’ll add them. One advantage to the Singleton approach might be that if we associate a valid data configuration with the class rather than the instance we can show one error message for the class. So in the case of the MPR views we would get 2 errors thrown rather than 4....

Or perhaps the application can combine the errors in a list view dialog....

**Comment by DominionSoftware** [comment]
I put in throw new Error("messages") but they get swallowed here in tracker.js:
 _compute() {
    this.invalidated = false;

    var previous = Tracker.currentComputation;
    setCurrentComputation(this);
    var previousInCompute = inCompute;
    inCompute = true;
    try {
      withNoYieldsAllowed(this._func)(this);
    } finally {
      setCurrentComputation(previous);
      inCompute = previousInCompute;
    }
  }

The try just does a finally, no errors are reported to the user.
I put in console.log() messages as well so that something will show up.

**Comment by swederik** [comment]
Oh that's interesting... I'll see if we can fix that

**Comment by DominionSoftware** [comment]
Is there more to do on this task?
