### ISSUE TITLE
Is there an example of CPR

### ISSUE THREAD

**Issue by wmxj** [OHIF/VTKPlugin#30]
Is there an example of CPR?tks

**Comment by dannyrb** [comment]
I'm not sure I follow. Do you have an example of the example you would like to see? Do you mean MPR?

**Comment by pieper** [comment]
I think @wmxj wants a curved reconstruction.  I'm sure you could do this with vtkjs, but I don't know that anyone has yet.

https://discourse.slicer.org/t/how-to-implement-cpr-curved-plannar-reconstruction-from-centerline/9456

**Comment by wmxj** [comment]
like this:http://blog.sina.com.cn/s/blog_8a35e5970102xurd.html
