### ISSUE TITLE
Add middle-click Pan (Dolly) interaction

### ISSUE THREAD

**Issue by swederik** [OHIF/VTKPlugin#4]
This has already been added here: https://github.com/DominionSoftware/Slicing/commit/1f8f013b4d5bec643cff34aecb2e0be07938bf7b

We need to add it to the plugin.

**Comment by DominionSoftware** [comment]
This is resolved by using left click - shift. I could not get the center mouse down-drag to work.

**Comment by swederik** [comment]
This is not resolved until middle click is implemented. I'll leave this open.

**Comment by DominionSoftware** [comment]
This is now fixed as of my initial merge.
