### ISSUE TITLE
Add Study/Series/Patient tags to the corners of the Viewport

### ISSUE THREAD

**Issue by swederik** [OHIF/VTKPlugin#7]
We will want this plugin to fit into the application smoothly, so it should have the same UI by default. Some of these tags are meaningless for volume renderings, e.g. Img 1 (1/108), window / level, etc.., but the rest should remain the same. The plugin should render these into the DIV, they should not be provided by OHIF.

![screenshot 2018-08-20 18 29 53](https://user-images.githubusercontent.com/607793/44353533-9587d180-a4a7-11e8-84d1-3565f9350034.png)

**Comment by DominionSoftware** [comment]
This is mostly done, zoom needs to be computed from the camera position. Date time format needs to be adjusted slightly.
